# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wOakayqM3PtxShbBSGFqBeV9Sqyxfq6f
"""

import spacy
from spacy.matcher import Matcher


terms_1 = [
    "next", "last", "after", "every"
  ]

terms_2 = [
    "today", "tomorrow", "year", "Monday", "Tuesday", "Wednesday", "Thursday",
    "Friday", "Saturday", "Sunday", "Jan", "Feb", "March", "Apr", "Jun", "Jul",
    "Aug", "Sep", "Oct", "Nov", "Dec", "January", "February", "March", "April",
    "June", "July", "August", "September", "October", "November", "December",
  ]

terms_3 = [
    "morning", "afternoon", "evening", "night", "week", "weeks", "month", "months",
    "year", "years"
  ]

pattern = ([
    {"LOWER": {"in": terms_1}, "OP": "?"},
    {"LEMMA": {"in": terms_2}, "OP": "?"},
    {"ENT_TYPE": {"in": ["DATE", "TIME"]}, "OP": "?"},
    {"ENT_TYPE": {"in": ["DATE", "TIME"]}, "OP": "?"},
    {"TEXT": ",", "OP": "?"},
    {"LOWER": {"in": terms_1}, "OP": "?"},
    {"LEMMA": {"in": terms_2}, "OP": "?"},
    {"ENT_TYPE": {"in": ["DATE", "TIME"]}, "OP": "?"},
    {"ENT_TYPE": {"in": ["DATE", "TIME"]}, "OP": "?"},
    {"LEMMA": {"in": terms_3}, "OP": "?"},
    {"LOWER": {"in": ["at", "on", "by", "from", "to", "before", "after", "between", "during", "in"]}, "OP": "?"},
    {"ENT_TYPE": {"in": ["DATE", "TIME"]}, "OP": "?"},
    {"ENT_TYPE": {"in": ["DATE", "TIME"]}, "OP": "?"},

  ])



text = input('Add your text message for meeting scheduling: ')

nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)
matcher.add("PATTERN",[pattern])
doc = nlp(text)
matchers = matcher(doc)

longest_match = None
max_length = 0
for index, start, end in matchers:
  lenght = end - start
  if lenght > max_length:
    max_length = lenght
    longest_match = (start , end)

if longest_match:
  start, end = longest_match
  print(f'{doc[:start]}_{doc[start:end]}_{doc[end:]}')
else:
  print("No date and time expressions found.")
