Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1qKnf-wwDFhPSLnfgyma7mbzEiKYAhwp7
"""

!pip3 install -U spacy

!python3 -m spacy download en_core_web_sm

import en_core_web_md
nlp = en_core_web_md.load()


# $python> message_parser.py < “How about SoKno tomorrow at 7.” ¬
# $ “How about SoKno *tomorrow* at *7*.” ¬
# or ¬
# $ “How about SoKno tomorrow at 7.” ¬
# Identify time and place prepositional phrases. Underline the time and, optional place. Recognize hours and minutes, days of the week, and a month.
# """

import spacy

# Input the message
TEXT = input('Add your text message for meeting schaduling:')


# Load SpaCy models
nlp = spacy.load("en_core_web_sm")
# nlp_md = spacy.load("en_core_web_md")

# Terms to highligt for meeting schaduling
terms = {'today', 'tomorrow',
         'Monday','Teusday','Wednesday','Thursday','Friday','Saturday','Sunday',
         'Jan', 'Feb', 'March', 'Apr', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
         '1', '2','3','4','5','6','7','8','9','10','11','12' }
ind = list()
s_new = ''

# Process the input text
doc = nlp(TEXT)

# Iterate through text
for i, s in enumerate(doc):
  print(s)
  if not s.is_stop:
    st = str(s.lemma_)
    if st in terms:
      st1 = "*" + str(s) + "*"
      ind.append(i)
      s_new = s_new + st1 + " "
      print(s_new)
  else:
    st1 = str(s)
    s_new = s_new + st1 + " "
    print(s_new)

print(s_new)

import spacy

# Input the message
TEXT = input('Add your text message for meeting schaduling:')


# Load SpaCy models
nlp = spacy.load("en_core_web_sm")
# nlp_md = spacy.load("en_core_web_md")

# Terms to highligt for meeting schaduling
terms = {
    'today', 'tomorrow',
    'Monday','Teusday','Wednesday','Thursday','Friday','Saturday','Sunday',
    'Jan', 'Feb', 'March', 'Apr', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    '1', '2','3','4','5','6','7','8','9','10','11','12'
}

for h in range(12+1):
  for m in range(1, 9+1):
    t = str(h) + ':' + '0' + str(m)
    terms.add(t)

  for n in range(10, 59+1):
    t = str(h) + ':' + str(n)
    terms.add(t)

ind = list()
s_new = ''

# Process the input text
doc = nlp(TEXT)

# Iterate through text
for i, s in enumerate(doc):

  st = str(s.lemma_)
  if st in terms:
    st1 = "*" + str(s) + "*"
    ind.append(i)
    s_new = s_new + st1 + " "

  else:
    st1 = str(s)
    s_new = s_new + st1 + " "

print(s_new)

import spacy

# Input the message
TEXT = input('Add your text message for meeting schaduling:')


# Load SpaCy models
nlp = spacy.load("en_core_web_sm")
# nlp_md = spacy.load("en_core_web_md")

# Terms to highligt for meeting schaduling
terms = {
    'today', 'tomorrow',
    'Monday','Teusday','Wednesday','Thursday','Friday','Saturday','Sunday',
    'Jan', 'Feb', 'March', 'Apr', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    '1', '2','3','4','5','6','7','8','9','10','11','12'
}

# Add hours and minutes as terms to highlight
for h in range(13):  # Hours from 0 to 12
    for m in range(60):  # Minutes from 0 to 59
        t = f"{h:01d}:{m:02d}"  # Format as HH:MM
        terms.add(t)

ind = list()
s_new = ''

# Process the input text
doc = nlp(TEXT)

# Iterate through text
for i, s in enumerate(doc):

  st = str(s.lemma_)
  if st in terms:
    st1 = "*" + str(s) + "*"
    ind.append(i)
    s_new = s_new + st1 + " "

  else:
    st1 = str(s)
    s_new = s_new + st1 + " "

print(s_new)
